{
 "title": "Monitoramento - Desafio DevOps Globo",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "description": "Status dos Apps",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=~\"app-python|app-go\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis - Clientes conectados",
   "type": "stat",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "redis_connected_clients", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memória",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"app-python|app-go\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis - Comandos por segundo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 6 },
   "targets": [
    {
     "expr": "rate(redis_commands_processed_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latência Média",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (job) (rate(app_latencia_requisicoes_segundos_sum[$__rate_interval]) / rate(app_latencia_requisicoes_segundos_count[$__rate_interval])) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requisições por Endpoint",
   "type": "stat",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job, endpoint) (app_requisicoes_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Taxa de requisições por App",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum by (job) (rate(app_requisicoes_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requisições por endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum by (job, endpoint) (app_requisicoes_total)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}